name: Combine Monthly Diaries

on:
  push:
    paths:
      - 'diary/*/[0-9][0-9]/*.md'
      - '!diary/*/monthly/*.md'

permissions:
  contents: write

jobs:
  combine_diaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Get changed diary files and their months
        id: changed_files
        run: |
          if git rev-parse --verify HEAD~1 &>/dev/null; then
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- 'diary/**/*.md' | grep -E '^diary/[0-9]{4}/[0-9]{2}/[0-9]{8}\.md$')
          else
            echo "HEAD~1 does not exist. Assuming initial push or single commit, processing all relevant diary files."
            CHANGED_FILES=$(git ls-files 'diary/**/*.md' | grep -E '^diary/[0-9]{4}/[0-9]{2}/[0-9]{8}\.md$')
          fi

          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant diary files found or changed in diary. Exiting."
            echo "should_run=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          AFFECTED_MONTHS_RAW=$(echo "$CHANGED_FILES" | sed -E 's|^diary/([0-9]{4})/([0-9]{2})/[0-9]{8}\.md$|\1/\2|' | sort -u)
          AFFECTED_MONTHS=$(echo "$AFFECTED_MONTHS_RAW" | tr '\n' ' ' | sed -E 's/ +$//')

          echo "Affected months: $AFFECTED_MONTHS"
          echo "affected_months=$AFFECTED_MONTHS" >> "$GITHUB_OUTPUT"
          echo "should_run=true" >> "$GITHUB_OUTPUT"

      - name: Combine daily diaries for affected months
        if: steps.changed_files.outputs.should_run == 'true'
        run: |
          for MONTH_PATH_YEAR_MONTH in ${{ steps.changed_files.outputs.affected_months }}; do
            YEAR=$(echo "$MONTH_PATH_YEAR_MONTH" | cut -d'/' -f1)
            MONTH=$(echo "$MONTH_PATH_YEAR_MONTH" | cut -d'/' -f2)

            .github/scripts/combine_diaries.sh "$YEAR" "$MONTH"

            git add "diary/${YEAR}/monthly/${YEAR}${MONTH}.md"
          done

      - name: Commit and push combined file
        if: steps.changed_files.outputs.should_run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git diff --cached --exit-code || git commit -m "Add/Update combined diary files (automated)"
          git push
