name: Combine Monthly Diaries

on:
  push:
    paths:
      - 'daily_diary/**/*.md'

jobs:
  combine_diaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true

      - name: Get changed diary files and their months
        id: changed_files
        run: |
          # 変更されたファイルを特定
          # HEAD~1 が存在するかどうかをチェックし、存在しない場合はリポジトリ内のすべての関連ファイルを対象にする
          if git rev-parse --verify HEAD~1 &>/dev/null; then
            # HEAD~1 が存在する場合、差分から変更されたファイルを取得
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- 'daily_diary/**/*.md' | grep -E '^daily_diary/[0-9]{4}/[0-9]{2}/[0-9]{8}\.md$')
          else
            # HEAD~1 が存在しない（最初のコミットなど）場合、リポジトリ内のすべての関連ファイルを取得
            echo "HEAD~1 does not exist. Assuming initial push or single commit, processing all relevant diary files."
            CHANGED_FILES=$(git ls-files 'daily_diary/**/*.md' | grep -E '^daily_diary/[0-9]{4}/[0-9]{2}/[0-9]{8}\.md$')
          fi

          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant diary files found or changed in daily_diary. Exiting."
            echo "::set-output name=should_run::false"
            exit 0
          fi

          AFFECTED_MONTHS=$(echo "$CHANGED_FILES" | sed -E 's|^daily_diary/([0-9]{4})/([0-9]{2})/[0-9]{8}\.md$|\1/\2|' | sort -u)

          echo "Affected months: $AFFECTED_MONTHS"
          echo "::set-output name=affected_months::$AFFECTED_MONTHS"
          echo "::set-output name=should_run::true"
          shell: /usr/bin/bash -e {0}
