name: Combine Monthly Diaries

on:
  push:
    paths:
      - 'daily_diary/**/*.md' 

jobs:
  combine_diaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # 最新の安定版Rubyバージョンを指定 (例: '3.3')
          bundler-cache: true # 依存関係がある場合はキャッシュ (Gemfileがある場合)

      - name: Get changed diary files and their months
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- 'daily_diary/**/*.md' | grep -E '^daily_diary/[0-9]{4}/[0-9]{2}/[0-9]{8}\.md$')
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant diary files changed in daily_diary. Exiting."
            echo "::set-output name=should_run::false"
            exit 0
          fi

          AFFECTED_MONTHS=$(echo "$CHANGED_FILES" | sed -E 's|^daily_diary/([0-9]{4})/([0-9]{2})/[0-9]{8}\.md$|\1/\2|' | sort -u)
          
          echo "Affected months: $AFFECTED_MONTHS"
          echo "::set-output name=affected_months::$AFFECTED_MONTHS"
          echo "::set-output name=should_run::true"

      - name: Combine daily diaries for affected months
        if: steps.changed_files.outputs.should_run == 'true'
        run: |
          for MONTH_PATH_YEAR_MONTH in ${{ steps.changed_files.outputs.affected_months }}; do
            YEAR=$(echo "$MONTH_PATH_YEAR_MONTH" | cut -d'/' -f1)
            MONTH=$(echo "$MONTH_PATH_YEAR_MONTH" | cut -d'/' -f2)
            
            .github/scripts/combine_diaries.sh "$YEAR" "$MONTH"
            
            git add "daily_diary/${YEAR}/${MONTH}/${YEAR}${MONTH}_combined.md"
          done

      - name: Commit and push combined file
        if: steps.changed_files.outputs.should_run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git diff --cached --exit-code || git commit -m "Add/Update combined diary files (automated)"
          git push
